config/routes.rb
Rails.application.routes.draw do
  
  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  post 'checkout' => 'cart#checkout'

  post 'order_complete' => 'cart#order_complete'

  post 'change_quantity' => 'cart#change_quantity'

  get 'remove_from_cart' => 'cart#remove_from_cart'

  resources :orders

  resources :line_items

  devise_for :users
  
  root 'storefront#all_items'

  get 'categorical' => 'storefront#items_by_category'

  get 'branding' => 'storefront#items_by_brand'

  resources :categories

  resources :products

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Tech Talent Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
  	<div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <%= link_to "Tech Talent Store", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Find By Category<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
          	<% Category.all.each do |cat| %>
	            <li><%= link_to cat.name, categorical_path(cat_id: cat.id) %></li>
	          <% end %>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Find By Brand<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
          	<% @brands.each do |brand| %>
	            <li><%= link_to brand, branding_path(brand: brand) %></li>
	          <% end %>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      	<li><%= link_to "My Cart", view_order_path %></li>
				<% if user_signed_in? %>
	        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
	        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
	      <% else %>
	        <li><%= link_to "Sign In",  new_user_session_path %></li>
        	<li><%= link_to "Forgot Password",  new_user_password_path %></li>
	      <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% for_device_type :desktop do %>
    <p>Desktop, laptop...not a phone or tablet.</p>
  <% end %>
  <% for_device_type :tablet do %>
    <p>You're on a tablet. That's so cool!</p>
  <% end %>
  <% for_device_type :mobile do %>
    <p>You're on a phone! Text me!</p>
  <% end %>
	<%= yield %>
</div>

</body>
</html>